import '../widgets/button/ui/button.css'
export { Button } from '../widgets/button/ui/button'
export { defineButtonAttributes } from '../widgets/button/api/buttonInterface'
export { Heroicon } from '../widgets/heroicon/ui/heroicon'
export { defineHeroiconAttributes } from '../widgets/heroicon/api/heroiconInterface'
